---
- name: Windows configuration with Ansible
  hosts: windows
  gather_facts: no
  tasks:
    - name: Join the VM to the domain
      import_tasks: roles/windows_config/tasks/domain_join.yml

    - name: Apply hardening policies
      import_tasks: roles/windows_config/tasks/hardening.yml

    - name: Install required software
      import_tasks: roles/windows_config/tasks/software_install.yml
