- name: Windows configuration with Ansible
  hosts: windows
  gather_facts: no
  vars:
    ansible_user: "{{ lookup('env', 'ansible_user') }}"
    ansible_password: "{{ lookup('env', 'ansible_password') }}"
    domain_admin_user: "{{ lookup('env', 'domain_admin_user') }}"
    domain_admin_password: "{{ lookup('env', 'domain_admin_password') }}"
    local_admin_user: "Administrator"

  tasks:
    - name: Mostrar credenciales usadas
      debug:
        msg: "Usuario: {{ domain_admin_user }} | Pass: {{ domain_admin_password }}"

  roles:
    - role: windows_config
